### ISSUE TITLE
repeated results

### ISSUE THREAD

**Issue by despoinamusica39** [mhmtbsrglu0/YouTubeMusicPython#1]
hello there!could you tell me please if your project shows repeated results?because I use one project with python but appear allways same results!!!

**Comment by mhmtbsrglu0** [comment]
are you talking about that ? That's normal because we're use while loop, if you find another problem you can contact me. **I'm gonna update next time** 

Note: copy + paste link   show your URL always.  Because that's a variable

![image](https://user-images.githubusercontent.com/75476607/105379215-acedba80-5c1d-11eb-9fa8-8746fc365229.png)
